# Generated by Django 3.2.5 on 2021-07-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=6)),
                ('modelo', models.CharField(max_length=30)),
            ],
        ),
    ]
